Added code for Checkov

diff --git a/.github/workflows/automation-pipeline.yml b/.github/workflows/automation-pipeline.yml
--- a/.github/workflows/automation-pipeline.yml
+++ b/.github/workflows/automation-pipeline.yml
@@ -50,7 +50,7 @@ jobs:
         if: steps.plan.outcome == 'failure'
         run: exit 1
         
-  static-code-analysis:
+  static-code-analysis-tflint:
     runs-on: ubuntu-latest
     needs: initial-setup
     timeout-minutes: 120
@@ -86,3 +86,41 @@ jobs:
 
       - name: Run TFLint
         run: tflint -f compact --force
+        
+  static-code-analysis-checkov:
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+      
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+    needs: static-code-analysis-tflint
+    timeout-minutes: 120
+    defaults:
+      run:
+        working-directory: tf
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
+      - uses: actions/checkout@v3
+
+      - name: Checkov GitHub Action
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          # This will add both a CLI output to the console and create a results.sarif file
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
+        
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v2
+        
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        # An alternative is to add `continue-on-error: true` to the previous step
+        # Or 'soft_fail: true' to checkov.
+        if: success() || failure()
+        with:
+          sarif_file: results.sarif
